import { Component } from '@angular/core';
import { Navbar } from "../../../layout/navbar/navbar";
import { MusicControl } from "../../../layout/music-control/music-control";
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-playlist-list',
  imports: [Navbar, MusicControl, CommonModule],
  templateUrl: './playlist-list.html',
  styleUrl: './playlist-list.scss'
})
export class PlaylistList {
  playlistData = [
    {
      number: 1,
      image: '../images/artist-img-7.png',
      song: 'Lost in the Echoes',
      artist: 'The Wanderers',
      album: 'Shadows of the Past',
      date: '03/03/2024',
      time: '3:03',
    },
    {
      number: 2,
      image: '../images/artist-img-6.png',
      song: 'Luna Waves',
      artist: 'Midnight Mirage',
      album: 'Dreamscapes',
      date: '04/17/2024',
      time: '5:22',
    },
    {
      number: 3,
      image: '../images/artist-img-8.png',
      song: 'Velvet Strings',
      artist: 'Heartfelt Harmony',
      album: 'Serenade of the Soul',
      date: '04/17/2024',
      time: '3:46',
    },
    {
      number: 4,
      image: '../images/artist-img-3.png',
      song: 'The Electric Suns',
      artist: 'Solar Flare',
      album: 'Galactic Journey',
      date: '04/17/2024',
      time: '1:55',
    },
    {
      number: 5,
      image: '../images/artist-img-2.png',
      song: 'Sapphire Sky',
      artist: 'Crystal Clear',
      album: 'Celestial Dreams',
      date: '04/17/2024',
      time: '2:40',
    },
    {
      number: 6,
      image: '../images/categ-img-5.png',
      song: 'Mystic Moon',
      artist: 'Enchanted Night',
      album: 'Twilight Whispers',
      date: '04/17/2024',
      time: '2:38',
    },
    {
      number: 7,
      image: '../images/categ-img-4.png',
      song: 'Aurora Echo',
      artist: 'Northern Lights',
      album: 'Aurora Borealis',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 8,
      image: '../images/artist-img-2.png',
      song: 'The Rhythm Riders',
      artist: 'Pulse of the City',
      album: 'Urban Beats',
      date: '04/17/2024',
      time: '3:28',
    },
    {
      number: 9,
      image: '../images/artist-img-3.png',
      song: 'Crimson Tide',
      artist: 'Deep Sea Symphony',
      album: 'Oceanic Reverie',
      date: '04/17/2024',
      time: '4:45',
    },
    {
      number: 10,
      image: '../images/artist-img-5.png',
      song: 'Golden Horizon',
      artist: 'Sunset Serenade',
      album: 'Dusk to Dawn',
      date: '04/17/2024',
      time: '6:45',
    },
    {
      number: 11,
      image: '../images/artist-img-1.png',
      song: 'Silver Strings',
      artist: 'Moonlit Melody',
      album: 'Starlit Nights',
      date: '04/17/2024',
      time: '6:45',
    },
    {
      number: 12,
      image: '../images/artist-img-5.png',
      song: 'Echoes of Eternity',
      artist: 'Timeless Tune',
      album: 'Forevermore',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 13,
      image: '../images/artist-img-3.png',
      song: 'The Velvet Vibe',
      artist: 'Smooth Operator',
      album: 'Groovy Nights',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 14,
      image: '../images/categ-img-5.png',
      song: 'Solar Symphony',
      artist: 'Sunburst',
      album: 'Daylight Dream',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 15,
      image: '../images/artist-img-3.png',
      song: 'The Dreamcatchers',
      artist: 'Fantasy Flight',
      album: 'Imaginarium',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 16,
      image: '../images/artist-img-2.png',
      song: 'Stardust Serenade',
      artist: 'Cosmic Dance',
      album: 'Nebula Nights',
      date: '04/17/2024',
      time: '4:15',
    },
    {
      number: 17,
      image: '../images/artist-img-1.png',
      song: 'The Harmonic Waves',
      artist: 'Ocean Breeze',
      album: 'Seaside Symphony',
      date: '04/17/2024',
      time: '4:15',
    },
  ];

}
